import { chromium } from '@playwright/test';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--no-sandbox'] });
const log = (k, v) => console.log(k.padEnd(34), v);
// desktop
let ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
let page = await ctx.newPage();
await page.goto('http://localhost:3000/', { waitUntil: 'networkidle' });
log('h1 text', await page.locator('h1').innerText());
log('heading order', (await page.locator('h1,h2,h3').evaluateAll(els => els.map(e => e.tagName).join(' '))).slice(0, 80) + '…');
await page.getElementById?.('about');
await page.evaluate(() => document.getElementById('about').scrollIntoView());
await page.waitForTimeout(500);
const card = page.locator('.idcard');
await card.click();
log('card flipped on click', await card.evaluate(e => e.classList.contains('is-flipped')));
await page.mouse.move(10, 10);
await card.focus(); await page.keyboard.press('Enter');
log('card after Enter', await card.evaluate(e => e.classList.contains('is-flipped')));
log('rig has rotate transform', await page.locator('.rig').evaluate(e => /rotate/.test(e.style.transform)));
await page.evaluate(() => document.getElementById('skills').scrollIntoView());
await page.waitForTimeout(400);
await page.getByRole('button', { name: 'HubSpot', exact: true }).click();
log('dimmed tiles after HubSpot filter', await page.locator('.el.is-dim').count() + ' / ' + await page.locator('.el').count());
await page.locator('.el').nth(12).hover();
await page.waitForTimeout(200);
log('inspector shows', (await page.locator('.ins-name').innerText()));
await page.evaluate(() => document.getElementById('work').scrollIntoView());
await page.locator('.panel').nth(2).hover();
await page.waitForTimeout(1000);
log('open panel index', await page.locator('.panel').evaluateAll(els => els.findIndex(e => e.classList.contains('is-open'))));
await page.evaluate(() => document.getElementById('achievements').scrollIntoView());
await page.waitForTimeout(1800);
log('first count-up value', await page.locator('.ach-num').first().innerText());
await page.evaluate(() => window.scrollBy(0, 1500)); await page.waitForTimeout(600);
log('track translated', await page.locator('.track').evaluate(e => e.style.transform));
await page.evaluate(() => document.getElementById('contact').scrollIntoView());
await page.waitForTimeout(400);
await ctx.grantPermissions(['clipboard-read', 'clipboard-write']);
await page.getByRole('button', { name: 'Copy' }).click();
await page.waitForTimeout(300);
log('copy chip text', await page.locator('.copy').innerText());
log('nav active', await page.locator('.pill a.is-active').innerText());
// keyboard focus style exists
await page.keyboard.press('Tab');
log('focused el outline', await page.evaluate(() => getComputedStyle(document.activeElement).outlineStyle));
await ctx.close();
// mobile menu
ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
page = await ctx.newPage();
await page.goto('http://localhost:3000/', { waitUntil: 'networkidle' });
await page.getByRole('button', { name: 'Menu' }).click();
await page.waitForTimeout(600);
log('overlay open', await page.locator('.overlay').evaluate(e => e.classList.contains('is-open')));
log('scroll locked', await page.evaluate(() => document.documentElement.style.overflow));
await page.keyboard.press('Escape');
await page.waitForTimeout(300);
log('overlay closed by Esc', !(await page.locator('.overlay').evaluate(e => e.classList.contains('is-open'))));
await page.evaluate(() => document.getElementById('work').scrollIntoView());
await page.waitForTimeout(300);
await page.locator('.wk-spine').nth(3).tap();
await page.waitForTimeout(500);
log('mobile accordion open index', await page.locator('.panel').evaluateAll(els => els.findIndex(e => e.classList.contains('is-open'))));
await page.evaluate(() => document.getElementById('about').scrollIntoView());
await page.waitForTimeout(300);
await page.locator('.idcard').tap();
log('card flips on tap', await page.locator('.idcard').evaluate(e => e.classList.contains('is-flipped')));
await ctx.close();
await browser.close();
